
theme: jekyll-theme-slate
markdown: kramdown
plugins_dir: ./_plugins


plugins:
  - jekyll-gist
  - jekyll-code-tabs

# Enable safe mode
safe: false

whitelist:
  - jekyll-gist
  - jekyll-code-tabs

exclude:
  - lib

