# This is a basic workflow to help you get started with Actions

name: Run selftest Godot 3.3.x

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout-branch:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: 'recursive'
          
  testing:
    needs: checkout-branch
    strategy:
      matrix:
        godot: [3.3, 3.3.1, 3.3.2, 3.3.3, mono-3.3.3]
    
    name: GdUnit3 Selftest on Godot ${{ matrix.godot }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ matrix.godot }}

    steps:
      - name: Setup
        shell: bash
        run: echo "GODOT_BIN=/usr/local/bin/godot" >> $GITHUB_ENV
          
      - name: Run Selftes
        shell: bash
        run: ./runtest.sh --selftest
          
      - name: Collect Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Report_${{ matrix.godot }}
          path: reports/**
